logging:
  level:
    org.springframework.web: debug
    org.hibernate: error
  file:
    name: logs/application.log

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:covid-registration}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    initialization-mode: always
    data: classpath:data.sql
  jackson:
    time-zone: GMT+4
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+4
    generate-ddl: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
welcome:
  message: Hello Thymeleaf
error:
  message: Error!

---
spring:
  profiles: test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

