logging:
  level:
    org.springframework.web: debug
    org.hibernate: error
  file:
    name: logs/application.log

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost/userDB
    username: postgres
    password: postgres
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
welcome:
  message: Hello Thymeleaf
error:
  message: Error!

---
spring:
  profiles: test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


